### ISSUE TITLE
Run detect.sh got a bad result

### ISSUE THREAD

**Issue by Anothorld** [ipl-uw/2019-CVPR-AIC-Track-3-UWIPL#2]
There is no visdrone.data in the darknet/cfg.
How can I get it.

**Comment by Anothorld** [comment]
In the detect.sh I use the original yolo3-voc.cfg file and voc.data but get a bad result. Is there some modification need to do on these files?

**Comment by Y-x-Y** [comment]
> In the detect.sh I use the original yolo3-voc.cfg file and voc.data but get a bad result. Is there some modification need to do on these files?

You need to use "visdrone.data" instead of "voc.data"

-XY

**Comment by Anothorld** [comment]
Thanks for replying and where can I find "visdrone.data"? There is no such file in the repo.

**Comment by Y-x-Y** [comment]
> Thanks for replying and where can I find "visdrone.data"? There is no such file in the repo.

Will let you know after I get back to my lab this weekend. I have no access to my desktop now.

**Comment by Anothorld** [comment]
> > Thanks for replying and where can I find "visdrone.data"? There is no such file in the repo.
> 
> Will let you know after I get back to my lab this weekend. I have no access to my desktop now.

OK :)

**Comment by LeoYeh97546** [comment]
There is no visdrone.data in the darknet/cfg.
How can I get it.

**Comment by LeoYeh97546** [comment]
And what is the output of that.
In models , you said "please use YOLO Candidate first to get anomaly candidates, and then use YOLO Robust on selected candidates. Those videos that are detected as candidates but do not detected by robust model will be sent into small object detection."  Where to use the robust model to detect?

**Comment by SamiurRahman1** [comment]
Did anyone find the visdrone.data file?

**Comment by Mandroide** [comment]
> Did anyone find the visdrone.data file?

Yes! The [visdrone_yolov3 repo](https://github.com/timforby/visdrone_yolov3.git)
